fragment ItemDelivery on CartItem {
    variantDelivery(zip: $zipCode) {
        end
        label
        start
    }
    variantInMarket(zip: $zipCode)
    variantInStock(zip: $zipCode)
}
query QuickCart($cartId: ID!, $zipCode: ZipCode!) {
    cart(cartId: $cartId) {
        id
        dynamicsVersion
        count
        coupons {
            id
            type
        }
        discount
        recyclingFee
        tax
        subTotal
        total
        ...@defer {
            items {
                categoryId
                categoryName
                categoryUrl
                count
                coupons {
                    id
                    type
                }
                id
                price
                productBadges {
                    label
                    type
                }
                productBrand
                productEyebrow
                productId(type: DYNAMICS)
                itemID: productId(type: MFRM)
                productImage
                productName
                productPromo
                productRating
                productRatingCount
                productUrl
                variantAttributes
                barCode: variantId(type: MFRM)
                variantId(type: DYNAMICS)
                ...ItemDelivery @defer
                variantOriginalPrice
                variantPrice
                variantType
                variantUrl
            }
        }
    }
}
